### ISSUE TITLE
Decimal numbers and comma as a decimal separator

### ISSUE THREAD

**Issue by romka0075** [SiaFoundation/web#288]
ui v0.16 in renterd 
If the default language in your browser uses a comma as a [decimal separator](https://en.wikipedia.org/wiki/Decimal_separator), you will not be able to use decimal numbers in the input fields. Dots in the input fields are ignored, commas give an error:
![Screenshot_20230519_001046](https://github.com/SiaFoundation/web/assets/96949156/7aeed32c-78ab-4886-b301-2a73e0ab1173)

How to reproduce:
1. Set your browser language to one that uses the comma as the decimal separator (Spanish, German, Russian, Polish, ...)
2. Try to enter a decimal number in the input field.

**Comment by alexfreska** [comment]
Thank you for this report. Localized number, currency, and date support has been added and will be available in the next release (ui v0.17.0). I will close this issue once that has been released and added to `renterd`.
