### ISSUE TITLE
Renter UX for when all contracts are ready

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/web#293]
One thing I am hitting a lot so far is it is unclear when the renter has enough contracts for uploading is "ready". How long it might take to form all contracts to start storing data is also unclear.

I think this needs to be given so that when you have a new seed/instance, you can see the progress of contracts and be told that you are ready to upload.

It may also be good for some numbers/graphs to simply say what is broken outside the data tables that exist.

Kudos!

**Comment by alexfreska** [comment]
Good point, we will figure out some UX around this.

**Comment by alexfreska** [comment]
Fixed https://github.com/SiaFoundation/renterd/pull/563
