### ISSUE TITLE
Price of announcement unclear

### ISSUE THREAD

**Issue by multikatt** [SiaFoundation/web#305]
## Describe the bug

When selecting announce host on the config page it says it'll cost 30.000 uS, but it really cost 30.000mS, which is correctly presented on wallet page.

![image](https://github.com/SiaFoundation/web/assets/389800/ef17ac61-b625-4c47-9b59-d3eb41fa42ff)
![image](https://github.com/SiaFoundation/web/assets/389800/e6e6e4c7-4742-4db2-af27-3c770b66eeef)

## Expected behaviour

30.000mS should be listed when confirming to broadcast the host.

**Comment by alexfreska** [comment]
Hey, nice catch, thank you for reporting this!

@n8maninger `/api/tpool/fee` is returning "30000000000000000000", is the endpoint pulling in the wrong value?
