### ISSUE TITLE
Customizable wallet page

### ISSUE THREAD

**Issue by multikatt** [SiaFoundation/web#358]
In renterd and hostd (and maybe walletd but have not used it) the amount of transactions visible is capped at 100. It would be nice to be able to see more than that, with pagination if needed. Also it would be great to be able to set a customizable time span on the balance graph on the top.

**Comment by timrettop** [comment]
I'd couple onto that request the ability to see the transaction details through a siascan link-out.

**Comment by alexfreska** [comment]
The transactions are now paginated and have siascan links. I will add a note about customizable balance evolution time spans to our backlog.
