### ISSUE TITLE
Remove lingering SiaStats links on website

### ISSUE THREAD

**Issue by skunk-ink** [SiaFoundation/web#407]
There are still a few links to SisStates on the site that should be removed.

sia.tech
![main_page](https://github.com/SiaFoundation/web/assets/22564783/005c74b5-60dd-45a2-ab97-b57174678b6c)

sia.tech/host
![host_page](https://github.com/SiaFoundation/web/assets/22564783/6d5f1d35-df57-4807-ad6c-a22e36290118)

sia.tech/learn
![learn_page](https://github.com/SiaFoundation/web/assets/22564783/94ee364c-7182-4c5f-a1cb-0933eeee968a)

**Comment by alexfreska** [comment]
Thank you for pointing these out, are all the other featured articles throughout the site still valid? would like to clean those up and point to fresh docs pages and content if possible.

**Comment by alexfreska** [comment]
I've removed the above 👍🏼
