### ISSUE TITLE
Add option to reset ephemeral account drift to host dropdown menu

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/web#524]
Using this endpoint https://api.sia.tech/renterd#2b3f27f7-cfaa-4005-8ffb-e986671fead5

**Comment by alexfreska** [comment]
@ChrisSchinnerl would we want this to reset the drift on all accounts or do we need a view where they can be listed and reset individually?

**Comment by ChrisSchinnerl** [comment]
@alexfreska Only one but we don't need a view that you can select from. Should be enough if you can click the account id from the alert and select "reset drift".
