### ISSUE TITLE
Add recommended tech specs to website software downloads

### ISSUE THREAD

**Issue by alexfreska** [SiaFoundation/web#553]

**Comment by alexfreska** [comment]
Currently updating the website download sections and noticed this ticket. What would the recommendations be for renterd cc @ChrisSchinnerl, hostd, and walletd cc @n8maninger?

**Comment by n8maninger** [comment]
`hostd`
- quad-core processor
- 8GB RAM
- 256GB SSD for consensus data
- 4TB HDD for stored data

**Comment by ChrisSchinnerl** [comment]
I'd do the same for `renterd` without the HDD.

`walletd` probably the same as `renterd` with 4GB of ram. (cc @n8maninger )

**Comment by n8maninger** [comment]
Might as well do 8GB for `walletd` too. It's a good happy medium.
