### ISSUE TITLE
Delete method for renterd-js

### ISSUE THREAD

**Issue by Siddharth-2382** [SiaFoundation/web#610]
I've recently started to migrate my whole renterd related fetching code to the new `renterd-js` library. But it's missing the ability to make a `DELETE` request i.e., the ability to delete data stored on a bucket using the worker api. Currently, it is providing with the `upload` & `download` methods only.

**Comment by alexfreska** [comment]
Hey, its great to hear you are able to use the SDK. I think you should be able to delete files with the `objectDelete` API:

```js
bus.objectDelete({
  params: {
    key: 'key/path.jpeg',
    bucket: 'photos',
    batch: false
   }
})
```
Or to delete all the files in a directory you can use the batch option:
```js
bus.objectDelete({
  params: {
    key: 'key/path/',
    bucket: 'photos',
    batch: true
   }
})
```
Let me know if this works for you.

**Comment by Siddharth-2382** [comment]
oh! I was tried doing this but was using it with `worker` and maybe it doesn't have that method yet?
